AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple DynamoDB table for global template directory example'

Resources:
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'example-app-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      Tags:
        - Key: Name
          Value: 'example-app-table'